security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            stateless: true
            entry_point: jwt
            json_login:
                check_path: api_login_check
                username_path: email
                password_path: plainPassword
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~
            refresh_jwt:
                check_path: /api/token/refresh
            logout:
                path: api_token_invalidate

    access_control:
        - {
              path: ^/api/(login_check|users|token/refresh),
              roles: PUBLIC_ACCESS,
              methods: [POST],
          }
        - { path: ^/api/verify-email, roles: PUBLIC_ACCESS }
        - { path: ^/api/resend-verification, roles: PUBLIC_ACCESS }
        # - { path: ^/api/users, roles: PUBLIC_ACCESS, methods: [POST] }
        # - { path: ^/api/login_check, roles: PUBLIC_ACCESS, methods: [POST] }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
